name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller chardet colorama
          
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --name sanity-exporter.exe --console sanity-exporter.py
          
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: sanity-exporter-windows
          path: dist/sanity-exporter.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller chardet colorama
          
      - name: Build Linux executable
        run: |
          pyinstaller --onefile --name sanity-exporter --console sanity-exporter.py
          
      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: sanity-exporter-linux
          path: dist/sanity-exporter

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller chardet colorama
          
      - name: Build macOS executable
        run: |
          pyinstaller --onefile --name sanity-exporter --console sanity-exporter.py
          
      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: sanity-exporter-macos
          path: dist/sanity-exporter

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare release assets
        run: |
          # Переименовываем файлы для ясности
          mv artifacts/sanity-exporter-windows/sanity-exporter.exe sanity-exporter-windows.exe
          mv artifacts/sanity-exporter-linux/sanity-exporter sanity-exporter-linux
          mv artifacts/sanity-exporter-macos/sanity-exporter sanity-exporter-macos
          
          # Добавляем права на выполнение для Linux и macOS
          chmod +x sanity-exporter-linux sanity-exporter-macos
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: |
            Automated build for Sanity Exporter ${{ github.ref_name }}
            - Windows: `sanity-exporter-windows.exe`
            - Linux: `sanity-exporter-linux`
            - macOS: `sanity-exporter-macos`
          files: |
            sanity-exporter-windows.exe
            sanity-exporter-linux
            sanity-exporter-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}